source 'https://rubygems.org'

ruby '~> 3.1.0'

gem 'rails', '~> 7.2.2', '>= 7.2.2.2'
gem 'rack', '~> 2.2.20'
gem "sprockets-rails"

group :development do
  gem 'warbler', github: 'jruby/warbler', branch: 'master'
  gem 'jruby-jars', '< 10'
end
