source 'https://rubygems.org'

ruby '~> 3.4.0'

gem 'rails', '~> 7.2.0'
gem 'rack', '~> 2.2'
gem 'sprockets-rails'

group :development do
  if !ENV['WARBLER_SRC']; gem 'warbler' else gem 'warbler', path: '../../../warbler' end
  if !ENV['JRUBY_RACK_SRC']; gem 'jruby-rack' else gem 'jruby-rack', path: '../../target' end
  gem 'jruby-jars', '~> 10'
end
