source 'https://rubygems.org'

ruby RUBY_VERSION

gem 'rails', '~> 7.2.0'
gem 'sprockets-rails'
gem 'rack', '~> 2.2.0'

group :development do
  gem 'jruby-jars', JRUBY_VERSION
  gem 'warbler'#, path: '../../../warbler'
  gem 'jruby-rack'#, path: '../../target/gem'
end
