# Servlet API friendly extensions to the Rack API
# Allows for forwarding the request to another servlet/JSP 
# as well as server-side include of content generated by a servlet/JSP
module Rack
  class Request
    def forward_to(path)
      servlet_request = env['java.servlet_request']
      servlet_response = env['java.servlet_response']
      servlet_request.getRequestDispatcher(path).forward(servlet_request, servlet_response)
    end

    def include(path)
      servlet_request = env['java.servlet_request']
      servlet_response = env['java.servlet_response']
      servlet_request.getRequestDispatcher(path).include(servlet_request, servlet_response)
    end
  end
end

