source 'https://rubygems.org'

ruby RUBY_VERSION

gem 'camping', '< 3'

group :development do
  gem 'jruby-jars', JRUBY_VERSION
  gem 'warbler'#, path: '../../../warbler'
  gem 'jruby-rack'#, path: '../../target/gem'
end
