source 'https://rubygems.org'

ruby '~> 3.1.0'

gem 'camping', '< 3'
gem 'rack', '~> 3.2.0'

group :development do
  if !ENV['WARBLER_SRC']; gem 'warbler' else gem 'warbler', path: '../../../warbler' end
  if !ENV['JRUBY_RACK_SRC']; gem 'jruby-rack' else gem 'jruby-rack', path: '../../target' end
  gem 'jruby-jars', '~> 9.4.0'
end
