source 'https://rubygems.org'

gem 'rack', '~> 2.2.0'
gem 'rackup'
gem 'camping', '< 3'
gem 'markaby'

group :development do
  gem 'warbler', github: 'jruby/warbler', branch: 'master'
  gem 'jruby-jars', '< 10'
end