source 'https://rubygems.org'

ruby RUBY_VERSION

gem 'rails', '~> 8.1.0'
gem 'rack', '~> 3.2.0'
gem 'sprockets-rails'

group :development do
  if !ENV['WARBLER_SRC']; gem 'warbler' else gem 'warbler', path: '../../../warbler' end
  if !ENV['JRUBY_RACK_SRC']; gem 'jruby-rack' else gem 'jruby-rack', path: '../../target' end
  gem 'jruby-jars', JRUBY_VERSION
end
