name: Java CI

on:
  push:
    branches: [ "master", "*-stable" ]
  pull_request:
    branches: [ "master", "*-stable" ]

env:
  # Default versions for canonical release build
  DEFAULT_JAVA_VERSION: '8'
  DEFAULT_JRUBY_VERSION: '10.0.6.0' # Should match pom.xml <jruby.compat.version> property (AND a version inside the test matrix)
  DEFAULT_RACK_VERSION: '~> 2.2.0' # Should match Gemfile (AND a version inside the test matrix)

jobs:
  build:
    name: Rack ${{ matrix.rack_version }} on JRuby ${{ matrix.jruby_version }} / Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jruby_version: [ '10.0.6.0', '10.1.1.0' ]
        java_version: [ '21', '25' ]
        rack_version: [ '~> 2.2.0' ]
      fail-fast: false

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: ./mvnw -ntp install -Dstyle.color=always -Djruby.test.version=${{ matrix.jruby_version }} -Djruby.compat.artifact=jruby-complete
      env:
        RACK_VERSION: ${{ matrix.rack_version }}

    # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5.0.0
      if: github.ref == 'refs/heads/master' && matrix.java_version == env.DEFAULT_JAVA_VERSION && matrix.jruby_version == env.DEFAULT_JRUBY_VERSION && matrix.rack_version == env.DEFAULT_RACK_VERSION

  appraisals:
    needs: build
    name: ${{ matrix.appraisal }} on ${{ matrix.jruby_version }} / Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        appraisal: [
          'rails72_rack22',
          'rails80_rack22',
        ]
        jruby_version: [ '10.0.6.0', '10.1.1.0' ]
        java_version: [ '21', '25' ]
      fail-fast: false

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.appraisal }}.gemfile

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: maven

      - name: Setup JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-${{ matrix.jruby_version }}
          bundler-cache: 'true'
          bundler: 'Gemfile.lock'

      - name: Remove jruby-launcher # Coming from setup-ruby/ruby-build and causes annoying warnings
        run: gem uninstall -a jruby-launcher

      - name: Run appraisal for ${{ matrix.appraisal }}
        run: bundle install && bundle exec rake spec

